//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class kurier
    {
        public int id_kurier { get; set; }
        public Nullable<int> klient { get; set; }
        public Nullable<int> zakaz { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Zakaz Zakaz1 { get; set; }
    }
}
