//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz()
        {
            this.kuriers = new HashSet<kurier>();
        }
    
        public int id_zakaz { get; set; }
        public Nullable<int> tovar { get; set; }
        public int quantity { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> klient { get; set; }
        public Nullable<int> Employee { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kurier> kuriers { get; set; }
        public virtual Tovar Tovar1 { get; set; }
    }
}
